# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Build
on: [pull_request, push, workflow_dispatch]

jobs:
  build-java:
    name: Build on Java
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: [21, 17]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: microsoft

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build
        
      - name: Capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: matrix-blocks-java-${{ matrix.java-version }}
          path: build/libs/*.jar
          if-no-files-found: error
