name: Compile Java
on: [pull_request, workflow_dispatch]

jobs:
  compile-java:
    name: Compile Java
    runs-on: ubuntu-latest
    matrix:
      java-version: [21, 17]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: microsoft
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Compile Java
        run: ./gradlew compileJava
      - name: Compile client-side Java
        run: ./gradlew compileClientJava
